$(function(){
    $('.editbar.foldbtn').click(function(){
        if($(this).attr('folded')=="false"){
            $(this).attr('folded','true');
            $(this).removeClass('glyphicon-resize-full');
            $(this).addClass('glyphicon-resize-large');
            $(this).parent().siblings("div").fadeOut();
        }
        else{
            $(this).attr('folded','false');
            $(this).removeClass('glyphicon-resize-full');
            $(this).addClass('glyphicon-resize-small');
            $(this).parent().siblings("div").fadeIn();
        }
    });
});